export const friends = [
  {
    id: "ishfaq",
    name: "Ishfaq",
    nickname: "Ish",
    bio: "The architect of our adventures. Every picnic starts with Ishfaq's wild ideas and impossible plans. He's the one who finds the most beautiful hidden spots in Kashmir and convinces everyone that a 6-hour trek is 'totally worth it.'",
    avatarUrl: "/images/friends/ishfaq.png",
    favoritePicnic: "2018 – Gurez Valley",
    favoriteLocation: "Gurez Valley",
    favoriteFood: "Kehwa & Bakery Biscuits",
    funFacts: [
      "Can navigate any Kashmiri road without Google Maps",
      "Takes exactly 47 photos of every sunset",
      "Once packed three jackets for a summer picnic 'just in case'",
      "Knows the name of every mountain peak visible from Srinagar"
    ],
    funnyHabits: [
      "Always arrives 30 minutes early and claims he's late",
      "Refuses to use a thermos – insists on making kehwa on a campfire",
      "Has a signature pose for every group photo",
      "Takes polaroid photos and stores them in a shoebox"
    ],
    awards: ["Chief Route Planner", "Official Sunset Photographer", "King of Overpacking"],
    role: "The Planner"
  },
  {
    id: "rouf",
    name: "Rouf",
    nickname: "Roufi",
    bio: "The soul of every gathering. Rouf brings the music, the laughter, and the chaos. He's the reason we have 200+ funny videos instead of 200 scenic photos. His energy is contagious and every picnic feels incomplete without his stories.",
    avatarUrl: "/images/friends/rouf.png",
    favoritePicnic: "2014 – Gulmarg Snow Day",
    favoriteLocation: "Gulmarg",
    favoriteFood: "Wazwan – Full Plate",
    funFacts: [
      "Knows every song released between 2005-2020",
      "Can fall asleep anywhere – including on a moving pony",
      "Once challenged a local to a cricket match during a picnic",
      "His phone has 15,000+ photos and zero free space"
    ],
    funnyHabits: [
      "Starts singing at the most random moments",
      "Always forgets to bring water but brings three Bluetooth speakers",
      "Gets lost even with GPS navigation",
      "Has been wearing the same picnic cap since 2016"
    ],
    awards: ["Entertainer of the Year (12 years running)", "Best Impressionist", "Official DJ"],
    role: "The Entertainer"
  },
  {
    id: "shoib",
    name: "Shoib",
    nickname: "Shobi",
    bio: "The quiet storm. Shoib doesn't say much, but when he does, it's either the wisest thing you've heard or the funniest. He's the photographer of the group, capturing candid moments that tell the real story of our friendship.",
    avatarUrl: "/images/friends/shoib.png",
    favoritePicnic: "2019 – Bangus Valley",
    favoriteLocation: "Bangus Valley",
    favoriteFood: "Gushtaba & Rogan Josh",
    funFacts: [
      "Has never missed a single picnic in 12 years",
      "Can cook a full meal on a portable stove in 20 minutes",
      "Secretly the best dancer among the three",
      "Keeps a handwritten journal of every picnic"
    ],
    funnyHabits: [
      "Always finds the perfect picnic spot before anyone else arrives",
      "Packs extra food 'for the journey back' and eats it all at the picnic",
      "Takes one serious photo for every ten silly ones",
      "Always says 'this is the best one yet' every single year"
    ],
    awards: ["Most Reliable Friend", "Best Cook", "Mr. Consistent", "Candid Photographer"],
    role: "The Anchor"
  }
];

export const picnics = [
  {
    year: 2013,
    title: "The Beginning – Pahalgam",
    date: "June 15, 2013",
    location: "Pahalgam, Anantnag",
    locationLat: 34.0161,
    locationLng: 75.3150,
    weather: "Sunny",
    temperature: "24°C",
    season: "Summer",
    budget: 2500,
    travelDistance: 95,
    transportation: "Shared Sumo",
    food: "Kehwa, bakery biscuits, sandwiches, fruits, nimbu paani",
    games: "Cricket, cards, antakshari",
    funnyMoments: "Rouf tried to cross the Lidder river on a makeshift rope bridge and fell in. We had to dry his clothes on tree branches while he sat in his underwear wrapped in a shawl. Ishfaq filmed the entire thing.",
    lessonsLearned: "Always carry extra clothes. Always check the depth of water before crossing.",
    mood: "Excited & Nervous",
    rating: 4.0,
    heroImageUrl: "/images/picnics/2013-pahalgam.png",
    description: "The picnic that started it all. Three friends, one sumo ride, and a lifetime of tradition. None of us knew this would become an annual ritual that would stretch over a decade.",
    route: "Srinagar → Pampore → Awantipora → Bijbehara → Anantnag → Pahalgam",
    travelNotes: "Left Srinagar at 7 AM. Stopped at Pampore for saffron fields photos. Had breakfast at a roadside dhaba near Awantipora. The road to Pahalgam was scenic but bumpy.",
    musicPlaylist: "Adele, AR Rahman, Kishore Kumar",
    drivingTime: "3 hours",
    nearbyAttractions: "Betaab Valley, Aru Valley, Chandanwari, Baisaran"
  },
  {
    year: 2014,
    title: "Snow Day – Gulmarg",
    date: "January 18, 2014",
    location: "Gulmarg, Baramulla",
    locationLat: 34.0484,
    locationLng: 74.3805,
    weather: "Heavy Snow",
    temperature: "-2°C",
    season: "Winter",
    budget: 4500,
    travelDistance: 50,
    transportation: "Personal Car",
    food: "Hot kehwa, pakoras, chocolate, dry fruits, coffee",
    games: "Snowball fight, making snowman, sledding",
    funnyMoments: "Shoib tried to make a snowman that ended up looking like a potato. Rouf insisted on going Gondola ride despite being terrified of heights. His face in the cable car photos is absolutely priceless.",
    lessonsLearned: "Winter picnics need serious preparation. Hand warmers are not optional – they're essential.",
    mood: "Thrilled & Freezing",
    rating: 4.5,
    heroImageUrl: "/images/picnics/2014-gulmarg.png",
    description: "Our first winter picnic! Gulmarg in January is a completely different world. We experienced snowfall like never before, rode the famous Gondola, and created memories that still make us laugh.",
    route: "Srinagar → Tangmarg → Gulmarg",
    travelNotes: "Roads were icy. Car slipped twice near Tangmarg. Shoib drove the entire way – legend. Reached Gulmarg by 10 AM. Gondola ride was magical.",
    musicPlaylist: "Coldplay, Ed Sheeran, Mohit Chauhan",
    drivingTime: "2 hours",
    nearbyAttractions: "Gondola Phase 1 & 2, Alpather Lake, Baba Reshi Shrine"
  },
  {
    year: 2015,
    title: "Glacier Dreams – Sonmarg",
    date: "July 20, 2015",
    location: "Sonmarg, Ganderbal",
    locationLat: 34.2790,
    locationLng: 75.3124,
    weather: "Partly Cloudy",
    temperature: "18°C",
    season: "Summer",
    budget: 3800,
    travelDistance: 87,
    transportation: "Shared Sumo",
    food: "Rajma chawal, pickle, roti, cucumber salad, mangoes",
    games: "Trekking, stone skipping, photography contest",
    funnyMoments: "Ishfaq tried to skip stones and accidentally hit Rouf's water bottle into the river. Rouf chased him for 15 minutes around the glacier. A group of tourists thought it was some kind of Kashmiri tradition.",
    lessonsLearned: "Don't stand downstream of Ishfaq when he's skipping stones.",
    mood: "Adventurous",
    rating: 4.7,
    heroImageUrl: "/images/picnics/2015-sonmarg.png",
    description: "Sonmarg – the meadow of gold. This was our most adventurous picnic yet. We trekked close to the Thajiwas Glacier, ate rajma chawal sitting on rocks, and witnessed nature at its rawest.",
    route: "Srinagar → Ganderbal → Kangan → Sonamarg",
    travelNotes: "Stopped at Kangan for fruits. The drive along the Sindh river is mesmerizing. Road conditions were decent. Reached by 9:30 AM.",
    musicPlaylist: "Linkin Park, Arijit Singh, Eminem",
    drivingTime: "2.5 hours",
    nearbyAttractions: "Thajiwas Glacier, Zoji La Pass, Baltal Valley, Vishansar Lake"
  },
  {
    year: 2016,
    title: "Milk White Streams – Doodhpathri",
    date: "May 28, 2016",
    location: "Doodhpathri, Budgam",
    locationLat: 34.0647,
    locationLng: 74.4278,
    weather: "Clear Sky",
    temperature: "20°C",
    season: "Spring",
    budget: 2000,
    travelDistance: 42,
    transportation: "Personal Car",
    food: "Kebabs, tandoori roti, raita, fruits, lassi",
    games: "Frisbee, badminton, running races, hide and seek",
    funnyMoments: "We played hide and seek like kids and Rouf hid behind a bush that turned out to have a beehive. He ran so fast that Usain Bolt would be proud. Shoib calmly ate his kebab while Rouf was being chased.",
    lessonsLearned: "Always inspect bushes before hiding behind them. Doodhpathri is heaven on earth.",
    mood: "Joyful & Carefree",
    rating: 4.8,
    heroImageUrl: "/images/picnics/2016-doodhpathri.png",
    description: "Doodhpathri – the Valley of Milk. The milky white streams, the endless green meadows, the pure air. This was the picnic where we felt like kids again, running through meadows without a care in the world.",
    route: "Srinagar → Budgam → Doodhpathri",
    travelNotes: "Shortest drive yet! The road from Budgam is beautiful. Stopped at a tea stall. Reached by 8:30 AM. The meadows were covered in wildflowers.",
    musicPlaylist: "Atif Aslam, Shreya Ghoshal, BTS",
    drivingTime: "1.5 hours",
    nearbyAttractions: "Nilnag Lake, Sukhnag, Yousmarg (nearby)"
  },
  {
    year: 2017,
    title: "Pine Forest Trails – Yusmarg",
    date: "August 12, 2017",
    location: "Yusmarg, Budgam",
    locationLat: 33.8375,
    locationLng: 74.4050,
    weather: "Light Rain",
    temperature: "16°C",
    season: "Monsoon",
    budget: 3200,
    travelDistance: 47,
    transportation: "Personal Car",
    food: "Wazwan (mini), naan, kehwa, chocolate cake",
    games: "Horse riding, trekking, card games in the rain",
    funnyMoments: "We rented horses and Shoib's horse decided to take a detour into the forest. Rouf's horse followed. Ishfaq had to rescue both of them while his own horse stood perfectly still, judging everyone.",
    lessonsLearned: "Horses have their own GPS. Always trust the horse more than the rider.",
    mood: "Peaceful & Mystical",
    rating: 4.3,
    heroImageUrl: "/images/picnics/2017-yusmarg.png",
    description: "Yusmarg – the meadow of Jesus. Dense pine forests, gentle horses, and the sound of rain on leaves. This monsoon picnic was unexpectedly magical. The mist in the forests created an atmosphere straight out of a fairy tale.",
    route: "Srinagar → Chadoora → Charar-e-Sharief → Yusmarg",
    travelNotes: "Stopped at Charar-e-Sharief shrine. The road to Yusmarg has some rough patches. Rain started just as we arrived – perfect timing.",
    musicPlaylist: "Rabbi Shergill, Zayn Malik, Pritam",
    drivingTime: "2 hours",
    nearbyAttractions: "Charar-e-Sharief, Doodhpathri, Nilnag Lake"
  },
  {
    year: 2018,
    title: "The Epic Journey – Gurez Valley",
    date: "September 8, 2018",
    location: "Gurez Valley, Bandipora",
    locationLat: 34.5789,
    locationLng: 74.8333,
    weather: "Clear & Crisp",
    temperature: "14°C",
    season: "Autumn",
    budget: 5500,
    travelDistance: 123,
    transportation: "Personal Car",
    food: "Packed lunch, maggi, tea, biscuits, dry fruits, chocolate",
    games: "Frisbee, photography, stargazing, bonfire stories",
    funnyMoments: "The drive through Razdan Pass was terrifying – Rouf screamed at every turn. When we finally reached Gurez, he kissed the ground. The locals thought we were filming a reality show.",
    lessonsLearned: "The scariest roads lead to the most beautiful destinations. Always carry motion sickness pills for Rouf.",
    mood: "Awestruck",
    rating: 4.9,
    heroImageUrl: "/images/picnics/2018-gurez.png",
    description: "Gurez Valley – the hidden gem of Kashmir. This was our most ambitious picnic. The 7-hour drive through the treacherous Razdan Pass was worth every second. The Habba Khatoon peak, the wooden houses, the Kishanganga river – Gurez felt like a different world entirely.",
    route: "Srinagar → Bandipora → Razdan Pass → Gurez",
    travelNotes: "Started at 5 AM. Filled up petrol in Bandipora (last petrol pump). Razdan Pass is 11,672 ft – had mild altitude sickness. Reached Gurez by noon. The valley was breathtaking. Stayed until evening for the sunset.",
    musicPlaylist: "Nusrat Fateh Ali Khan, Shafqat Amanat Ali, A. R. Rahman",
    drivingTime: "4 hours (one way)",
    nearbyAttractions: "Habba Khatoon Peak, Kishanganga River, Razdan Pass, Tulail Valley"
  },
  {
    year: 2019,
    title: "The Untouched Paradise – Bangus Valley",
    date: "July 6, 2019",
    location: "Bangus Valley, Kupwara",
    locationLat: 34.4672,
    locationLng: 74.0917,
    weather: "Perfect Sunshine",
    temperature: "22°C",
    season: "Summer",
    budget: 4800,
    travelDistance: 110,
    transportation: "Personal Car + Trek",
    food: "Sandwiches, fruits, juice, energy bars, biryani",
    games: "Trekking, photography, cloud watching, storytelling",
    funnyMoments: "The trek to Bangus was supposed to be 'easy.' Two hours in, Rouf sat down and refused to move. Ishfaq had to literally drag him the last kilometer. When we reached the valley, Rouf said 'this was worth dying for' and we all lost it.",
    lessonsLearned: "When Ishfaq says 'easy trek,' add at least 2 hours to his estimate. Bangus is worth every step.",
    mood: "Exhausted & Ecstatic",
    rating: 5.0,
    heroImageUrl: "/images/picnics/2019-bangus.png",
    description: "Bangus Valley – Kashmir's best-kept secret. This untouched paradise required a trek, but what awaited us was beyond words. Miles of unspoiled meadows, wildflowers as far as the eye could see, and not another soul around. Pure, undisturbed nature.",
    route: "Srinagar → Baramulla → Kupwara → Handwara → Trek to Bangus",
    travelNotes: "Left at 4 AM. The drive to the trek starting point took 3 hours. The trek was 8 km (Ishfaq lied about it being 4 km). Reached the valley by noon. It was absolutely magnificent.",
    musicPlaylist: "Ed Sheeran, Arijit Singh, Coldplay, Mohit Chauhan",
    drivingTime: "3 hours drive + 2 hours trek",
    nearbyAttractions: "Rajwar, Lolab Valley, Karnah"
  },
  {
    year: 2020,
    title: "The Rooftop Reunion – Srinagar",
    date: "October 11, 2020",
    location: "Rooftop, Srinagar",
    locationLat: 34.0837,
    locationLng: 74.7973,
    weather: "Cool & Crisp",
    temperature: "15°C",
    season: "Autumn",
    budget: 1500,
    travelDistance: 5,
    transportation: "Walking",
    food: "Kehwa, harissa, tandoori chicken, naan, firni",
    games: "Cards, dumb charades, music, reminiscing",
    funnyMoments: "We couldn't travel far due to restrictions, so we did a rooftop picnic at Shoib's place. Rouf brought his entire speaker setup for a 'small gathering.' The neighbors definitely did not appreciate the 2 AM a cappella session.",
    lessonsLearned: "You don't need to go far to make memories. Sometimes the best picnics happen on rooftops with your best friends.",
    mood: "Grateful & Warm",
    rating: 4.2,
    heroImageUrl: "/images/picnics/2020-srinagar.png",
    description: "The year that changed everything. When the world stopped, our tradition didn't. We had a rooftop picnic overlooking Dal Lake – simple, intimate, and perfect. This picnic taught us that friendship doesn't need exotic locations.",
    route: "Everyone's home → Shoib's rooftop",
    travelNotes: "The simplest picnic of all. Everyone walked to Shoib's place. Set up on the rooftop with a view of Dal Lake and the Zabarwan hills. Chinar leaves were changing color – golden autumn.",
    musicPlaylist: "Old Bollywood classics, Kashmiri songs, retro mix",
    drivingTime: "10 minutes walk",
    nearbyAttractions: "Dal Lake, Mughal Gardens, Shankaracharya Temple"
  },
  {
    year: 2021,
    title: "Above the Clouds – Sinthan Top",
    date: "June 19, 2021",
    location: "Sinthan Top, Kishtwar Road",
    locationLat: 33.5650,
    locationLng: 75.5883,
    weather: "Cloudy with Sun Breaks",
    temperature: "12°C",
    season: "Summer",
    budget: 4000,
    travelDistance: 130,
    transportation: "Personal Car",
    food: "Packed biryani, raita, salad, cold coffee, cookies",
    games: "Photography, cloud watching, singing, exploring",
    funnyMoments: "We drove through clouds to reach Sinthan Top. Rouf was convinced we had died and gone to heaven. When the clouds parted and we saw the view, even Ishfaq was speechless – and that almost never happens.",
    lessonsLearned: "Some places are so beautiful they make you forget how to speak. Always carry warm clothes to high-altitude passes.",
    mood: "Mystical & Speechless",
    rating: 4.6,
    heroImageUrl: "/images/picnics/2021-sinthan.png",
    description: "Sinthan Top – where earth meets sky. At 12,500 feet, we drove through literal clouds. The road was narrow and winding, but the destination was surreal. We sat at the top, above the clouds, eating biryani like kings of the world.",
    route: "Srinagar → Anantnag → Kokernag → Sinthan Pass → Sinthan Top",
    travelNotes: "Started at 5 AM. Stopped at Kokernag springs. The climb to Sinthan Top is steep and narrow. Passed through dense clouds. Temperature dropped significantly. The view at the top was otherworldly.",
    musicPlaylist: "Imagine Dragons, Arijit Singh, Queen, Atif Aslam",
    drivingTime: "4 hours",
    nearbyAttractions: "Kokernag Gardens, Verinag Spring, Achabal"
  },
  {
    year: 2022,
    title: "Thundering Waters – Aharbal",
    date: "May 14, 2022",
    location: "Aharbal, Kulgam",
    locationLat: 33.5550,
    locationLng: 74.5500,
    weather: "Warm & Sunny",
    temperature: "26°C",
    season: "Spring",
    budget: 2800,
    travelDistance: 68,
    transportation: "Personal Car",
    food: "Tikka, naan, chutney, fruit chaat, lassi, gulab jamun",
    games: "Swimming (dangerous but Rouf tried), stone skipping, photography, cards",
    funnyMoments: "Rouf decided to swim in the waterfall pool despite our warnings. He lasted exactly 12 seconds before the current pulled him. Shoib fished him out while Ishfaq captured the whole rescue mission on video.",
    lessonsLearned: "Waterfalls are beautiful but powerful. Never underestimate the current. Always have a friend who can actually swim.",
    mood: "Refreshed & Alive",
    rating: 4.4,
    heroImageUrl: "/images/picnics/2022-aharbal.png",
    description: "Aharbal – the Niagara of Kashmir. The thundering waterfall, the deep green pool, and the surrounding pine forests made this picnic unforgettable. The sound of the waterfall was our music, and the mist was our air conditioning.",
    route: "Srinagar → Pulwama → Shopian → Aharbal",
    travelNotes: "Drive through Shopian is beautiful with apple orchards. Road from Shopian to Aharbal has some rough patches. The sound of the waterfall can be heard before you even see it.",
    musicPlaylist: "AP Dhillon, Raftaar, Diljit Dosanjh, Sidhu Moose Wala",
    drivingTime: "2.5 hours",
    nearbyAttractions: "Kousarnag Lake, Shopian Apple Orchards, Hirpora Wildlife Sanctuary"
  },
  {
    year: 2023,
    title: "Blossom Trail – Lolab Valley",
    date: "April 8, 2023",
    location: "Lolab Valley, Kupwara",
    locationLat: 34.3000,
    locationLng: 74.2500,
    weather: "Mild & Pleasant",
    temperature: "18°C",
    season: "Spring",
    budget: 3000,
    travelDistance: 105,
    transportation: "Personal Car",
    food: "Nun chai, bakery items, kebabs, fruits, halwa",
    games: "Cricket in the meadow, cycling, photography, kite flying",
    funnyMoments: "We arrived during apple blossom season and Shoib spent 45 minutes photographing flowers while Rouf tried to climb an apple tree. He got stuck on a branch for 20 minutes. Ishfaq calmly ate all the halwa while 'rescuing' him.",
    lessonsLearned: "Spring in Kashmir's valleys is magical. Don't try to climb trees in your picnic clothes.",
    mood: "Fresh & Renewed",
    rating: 4.5,
    heroImageUrl: "/images/picnics/2023-lolab.png",
    description: "Lolab Valley – the land of springs and blossoms. We timed this picnic perfectly with the apple blossom season. The entire valley was painted in shades of pink and white. It was like walking through a living painting.",
    route: "Srinagar → Baramulla → Kupwara → Lolab Valley",
    travelNotes: "The drive through Baramulla and Kupwara is scenic. Lolab Valley is surprisingly unexplored. The springs (Gagangir, Kalaroos) are crystal clear. Apple orchards were in full bloom.",
    musicPlaylist: "Pritam, Vishal-Shekhar, Shreya Ghoshal, Arijit Singh",
    drivingTime: "3 hours",
    nearbyAttractions: "Kalaroos Caves, Gagangir Spring, Chandigam, Kupwara"
  },
  {
    year: 2024,
    title: "Riverside Serenity – Keran",
    date: "July 27, 2024",
    location: "Keran, Kupwara",
    locationLat: 34.5333,
    locationLng: 74.3500,
    weather: "Warm & Sunny",
    temperature: "25°C",
    season: "Summer",
    budget: 4200,
    travelDistance: 115,
    transportation: "Personal Car",
    food: "Wazwan, rice, salad, kehwa, cake, fruits",
    games: "Cricket, swimming in safe zones, fishing, bonfire, singing",
    funnyMoments: "We celebrated 12 years with a proper wazwan feast by the river. Rouf tried to fish with a stick and thread. He actually caught something – a water bottle. Ishfaq declared it 'the biggest catch of the day.' We laughed until we cried.",
    lessonsLearned: "Twelve years of friendship is the greatest treasure. The river doesn't care about your fancy fishing equipment.",
    mood: "Nostalgic & Grateful",
    rating: 4.8,
    heroImageUrl: "/images/picnics/2024-keran.png",
    description: "Keran – where the Neelum River sings. Our 12th annual picnic, and what a way to celebrate! The crystal-clear Neelum River, the green mountains on both sides, and a full wazwan feast. We reflected on 12 incredible years and promised 12 more.",
    route: "Srinagar → Baramulla → Kupwara → Handwara → Keran",
    travelNotes: "Left at 5:30 AM. The road improved significantly this year. Stopped at Kupwara for supplies. Reached Keran by 9:30 AM. Set up our picnic spot right by the river. Perfect weather. Stayed until sunset.",
    musicPlaylist: "12 years of friendship playlist – every song that reminds us of each picnic",
    drivingTime: "3.5 hours",
    nearbyAttractions: "Neelum River, Taobat, Surgan, Sharda Peeth"
  }
];

export const galleryPhotos = [
  { id: "g1", url: "/images/gallery/campfire.png", caption: "Stories by the campfire – 2017 Gurez", year: 2017, category: "campfire", tags: ["campfire", "night", "friends"] },
  { id: "g2", url: "/images/gallery/food.png", caption: "Our traditional Kashmiri feast – 2020", year: 2020, category: "food", tags: ["food", "wazwan", "kashmiri"] },
  { id: "g3", url: "/images/gallery/hiking.png", caption: "The legendary trek to Bangus – 2019", year: 2019, category: "travel", tags: ["hiking", "trek", "mountains"] },
  { id: "g4", url: "/images/gallery/sunrise.png", caption: "Sunrise at Dal Lake – 2020", year: 2020, category: "sunrise", tags: ["sunrise", "dal-lake", "morning"] },
  { id: "g5", url: "/images/gallery/selfie.png", caption: "Summit selfie at Sinthan Top – 2021", year: 2021, category: "selfies", tags: ["selfie", "summit", "adventure"] },
  { id: "g6", url: "/images/gallery/rain.png", caption: "Dancing in the rain – Yusmarg 2017", year: 2017, category: "rain", tags: ["rain", "monsoon", "umbrella"] },
  { id: "g7", url: "/images/gallery/bridge.png", caption: "Crossing the stream – Doodhpathri 2016", year: 2016, category: "travel", tags: ["bridge", "stream", "nature"] },
  { id: "g8", url: "/images/gallery/sunset-silhouette.png", caption: "Golden hour at Gurez – 2018", year: 2018, category: "sunset", tags: ["sunset", "silhouette", "mountains"] },
  { id: "g9", url: "/images/hero/kashmir-valley.png", caption: "The valley that binds us", year: 2018, category: "nature", tags: ["kashmir", "valley", "mountains"] },
  { id: "g10", url: "/images/hero/gulmarg-meadows.png", caption: "Gulmarg meadows in bloom", year: 2014, category: "nature", tags: ["gulmarg", "meadows", "flowers"] },
  { id: "g11", url: "/images/picnics/2013-pahalgam.png", caption: "Where it all began – Pahalgam 2013", year: 2013, category: "nature", tags: ["pahalgam", "beginning", "river"] },
  { id: "g12", url: "/images/picnics/2015-sonmarg.png", caption: "Glacier adventure – Sonmarg 2015", year: 2015, category: "nature", tags: ["sonmarg", "glacier", "adventure"] },
];

export const quotes = [
  { id: "q1", text: "A true friend is the greatest of all blessings.", author: "Francois de La Rochefoucauld", year: 2013 },
  { id: "q2", text: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", author: "C.S. Lewis", year: 2014 },
  { id: "q3", text: "In the sweetness of friendship let there be laughter, for in the dew of little things the heart finds its morning.", author: "Khalil Gibran", year: 2015 },
  { id: "q4", text: "Rouf, if you fall in that river one more time, I'm leaving you here.", author: "Ishfaq, 2013", year: 2013, context: "After Rouf's second fall into Lidder river" },
  { id: "q5", text: "This is the best one yet.", author: "Shoib (every single year)", year: 2016 },
  { id: "q6", text: "Life was meant for good friends and great adventures.", author: "Unknown", year: 2017 },
  { id: "q7", text: "Rouf's face in the Gondola should be framed and hung in a museum.", author: "Shoib, 2014", year: 2014, context: "Commenting on Rouf's terrified expression during the Gulmarg Gondola ride" },
  { id: "q8", text: "Guys, I think we're actually doing this for the rest of our lives.", author: "Ishfaq, 2018", year: 2018, context: "Realizing the tradition while watching sunset at Gurez" },
  { id: "q9", text: "Some people arrive and make such a beautiful impact on your life, you can barely remember what life was like without them.", author: "Anna Taylor", year: 2019 },
  { id: "q10", text: "The biggest catch of the day!", author: "Ishfaq, 2024", year: 2024, context: "After Rouf 'caught' a water bottle while fishing at Keran" },
  { id: "q11", text: "We didn't realize we were making memories. We just knew we were having fun.", author: "Winnie the Pooh", year: 2020 },
  { id: "q12", text: "Twelve years, twelve picnics, a million laughs. And we're just getting started.", author: "The Friendship Vault", year: 2024 },
];

export const stories = [
  {
    id: "s1",
    title: "The First Step",
    content: "It was June 2013. Three friends with ₹2500 and a crazy idea. 'Let's go to Pahalgam,' Ishfaq said. Rouf agreed immediately. Shoib packed the food. None of us knew this would become the most important tradition of our lives. We were just three young guys wanting an adventure. That first picnic had no plan, no expectations, no idea of what was to come. And maybe that's what made it perfect.",
    year: 2013,
    mood: "Nostalgic",
    friendId: "ishfaq"
  },
  {
    id: "s2",
    title: "The Day Rouf Conquered His Fear",
    content: "The Gondola at Gulmarg goes up to 13,780 feet. Rouf is terrified of heights. But in 2014, surrounded by snow and his two best friends egging him on, he stepped into that cable car with shaking legs. His face went through about 15 different shades. He gripped the handrail so hard his knuckles turned white. But when he saw the view from the top – the entire Pir Panjal range covered in snow – he forgot his fear for exactly 3 seconds. Then he remembered and refused to look down for the rest of the ride. That's courage, Rouf-style.",
    year: 2014,
    mood: "Hilarious",
    friendId: "rouf"
  },
  {
    id: "s3",
    title: "The Stone That Changed Everything",
    content: "At Sonmarg in 2015, Ishfaq picked up a stone and tried to skip it across the glacial stream. The stone had other plans. It ricocheted off the water and hit Rouf's water bottle – which was perched on a rock – straight into the rushing river. What followed was a 15-minute chase scene through glacier territory. Ishfaq running, Rouf chasing, Shoib sitting on a rock eating an apple and recording everything. The stone-skip incident became our most referenced inside joke. To this day, if someone says 'nice throw,' all three of us lose it.",
    year: 2015,
    mood: "Funny",
    friendId: "ishfaq"
  },
  {
    id: "s4",
    title: "Shoib's Speech",
    content: "It was getting dark at Gurez in 2018. We were sitting by the Kishanganga river, the stars were coming out, and the Habba Khatoon peak was silhouetted against the night sky. Without any warning, Shoib said: 'You know, if someone had told 15-year-old me that I'd be sitting in one of the most remote valleys on earth with my two best friends, eating maggi and watching stars, I wouldn't have believed them. But here we are. And I wouldn't trade this for anything.' We sat in silence for a full minute after that. Then Rouf ruined it by asking if anyone brought more maggi. But that minute of silence was perfect.",
    year: 2018,
    mood: "Emotional",
    friendId: "shoib"
  },
  {
    id: "s5",
    title: "When the World Stopped, We Didn't",
    content: "2020 was supposed to be our most ambitious picnic yet – we planned to visit Drass, the second coldest inhabited place on earth. But the world had other plans. For months, we couldn't meet, couldn't travel, couldn't do anything. But when October came, we decided: the tradition continues. We met at Shoib's rooftop with a simple spread of kehwa and harissa. The view of Dal Lake was beautiful. The chinar trees were golden. And we realized something important: you don't need mountains and rivers for a picnic. You just need your people.",
    year: 2020,
    mood: "Reflective",
    friendId: "shoib"
  }
];

export const guestbookEntries = [
  { id: "gb1", name: "Auntie Shamima", message: "I've watched you three grow up together. May your friendship last forever. Your picnic photos make my day every time you share them! 💚", emoji: "💚", createdAt: "2024-03-15T10:00:00Z" },
  { id: "gb2", name: "Danish (Cousin)", message: "Can I join next year's picnic? Asking for a friend... okay fine, asking for myself. You guys are lucky to have each other! 😄", emoji: "😄", createdAt: "2024-06-20T14:30:00Z" },
  { id: "gb3", name: "Farah", message: "This website is the most beautiful thing I've seen. Friendship like yours is rare. Never let it go! 🏔️", emoji: "🏔️", createdAt: "2024-07-01T09:15:00Z" },
  { id: "gb4", name: "Uncle Mohammad", message: "I remember when you boys were kids playing cricket in the lane. Now look at you – exploring all of Kashmir! Makes an old man proud. 🙏", emoji: "🙏", createdAt: "2024-08-10T16:45:00Z" },
  { id: "gb5", name: "Sana", message: "The Gurez photos are absolutely stunning! You three should start a travel blog. Also, Rouf's Gondola face is iconic 😂", emoji: "😂", createdAt: "2024-09-05T11:20:00Z" },
];

export const statistics = {
  yearsTogether: 12,
  totalPicnics: 12,
  totalPhotos: 8742,
  totalVideos: 342,
  totalStories: 48,
  voiceNotes: 23,
  locationsVisited: 12,
  distanceTravelled: 1071,
  moneySpent: 41800,
  mealsShared: 96,
  gamesPlayed: 48,
  campfires: 8,
  rainyTrips: 3,
  sunnyTrips: 6,
  averagePhotosPerTrip: 729,
  averageVideosPerTrip: 29,
  mostVisitedPlace: "Gulmarg & Pahalgam (tied)",
  favoriteFood: "Kehwa & Bakery Biscuits",
  favoriteSeason: "Summer",
  longestTrip: "Gurez Valley 2018 (248 km round trip)",
  shortestTrip: "Rooftop 2020 (5 km)",
  friendWithMostPhotos: "Ishfaq (the designated photographer)"
};